### ISSUE TITLE
Adblock Blacklist

### ISSUE THREAD

**Issue by BlackJack8** [dead-hosts/dev-center#11]
**Is your list in a Git repository? List them here**

* Repository Name
iOSAdblockList
 
 * repository link
https://github.com/BlackJack8/iOSAdblockList

  * Lists to test:
    * Raw Link of the first list to test
https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Hosts.txt

    * Raw Link of the second list to test
https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Miscellaneous(Hosts).txt

    * Raw Link of the third list to test
_______________

Please note:
Both lists above are available with resolvers behind each domain, if that is important.

Thank you for your effort!

**Comment by funilrys** [comment]
Moved to "waiting" as our infrastructure tool is not working right now. It has probably something to do with the Travis CI API issue a few hours ago.

I don't have the time to do all the things (for repository creation/setup) manually. So let me check it out. 
I added this repo to my high-prio kanban so that I don't miss it after fixing the tool.
