### ISSUE TITLE
dead-hosts/hosts_git_tyzbit can be removed

### ISSUE THREAD

**Issue by tyzbit** [dead-hosts/dev-center#2]
Since the removal of my hosts file from https://github.com/StevenBlack/hosts, it has become unnecessary to continue to check my hosts entries for dead hosts.

Please remove https://github.com/dead-hosts/hosts_git_tyzbit/

**Comment by funilrys** [comment]
Hi @tyzbit,
Because the generated data/list may be used, I just removed the ping.

Indeed, in my process, the system still continue the cleaning of the local file even if the upstream links are not active/dead. I did not think about this case that much.

I will archive the mentioned repository maybe later next year after updating/enhancing my internal processes.

Merry Chrismas,
Cheers,
Nissar

P.S: Closing but kept open in my personal backlog.
