### ISSUE TITLE
The .PyFunceble.yaml configuration file is sometimes changed after running the Action

### ISSUE THREAD

**Issue by bigdargon** [dead-hosts/dev-center#24]
Dead hosts is a great project! Thank you very much for it! But sometimes the file `.PyFunceble.yaml` is changed to the default (not the default file from the template).

Check it out here https://github.com/bigdargon/hostsVN-dead-hosts/commits/master/.pyfunceble/.PyFunceble.yaml

The config file https://github.com/bigdargon/hostsVN-dead-hosts/commit/2ca2e27327ffd59e5270af1a343cfaaafcc6f856 was randomly changed to the following causing the Action to fail https://github.com/bigdargon/hostsVN-dead-hosts/runs/5975137921?check_suite_focus=true

Then I had to manually delete the config file https://github.com/bigdargon/hostsVN-dead-hosts/commit/baea5331582b4c6d7551a474d15253ce581ec3ad, for the Actions to work again https://github.com/bigdargon/hostsVN-dead-hosts/runs/5975484975?check_suite_focus=true

Thank you again for this project!

**Comment by funilrys** [comment]
Hi @bigdargon , yes, that's why you should change the `.PyFunceble.overwrite.yaml` file instead. (CF: https://pyfunceble.readthedocs.io/en/latest/configuration/index.html#filename-s)

Or put your own configuration as a json inside the `custom_pyfunceble_config` index of your `info.json` file.

Stay safe and healthy!
