### ISSUE TITLE
X Files modules inclusion request

### ISSUE THREAD

**Issue by gioxx** [dead-hosts/dev-center#4]
* Repository Name: xfiles
  * repository link: https://github.com/gioxx/xfiles/
  * Lists to test:
    * https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt
    * https://raw.githubusercontent.com/gioxx/xfiles/master/facebook.txt
    * https://raw.githubusercontent.com/gioxx/xfiles/master/siteblock.txt
    * https://raw.githubusercontent.com/gioxx/xfiles/master/nocoin.txt

Thanks!

**Comment by funilrys** [comment]
Hi @gioxx,

It's in my queue 🙂 Once created, you'll get an invitation to join one of our team so that you can manage them.

**Note: There is a pending issue (https://github.com/funilrys/PyFunceble/issues/42) regarding the decoding of filter lists. So please don't panic if you see inaccurate results. It will be fixed (and will be available in our infrastructure) asap.**

Cheers,
Nissar

**Comment by funilrys** [comment]
@gioxx Sorry for the delay had some issue to fix with the automation tool, It's done. 

Please look at your notifications for the invitation to join the team or follow https://github.com/dead-hosts.

Cheers,
Nissar
