### ISSUE TITLE
AdBlockID

### ISSUE THREAD

**Issue by realodix** [dead-hosts/dev-center#9]
**Is your list in a Git repository? List them here**

* AdBlockID
  * https://github.com/realodix/AdBlockID
  * Lists to test:
    * https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt
    * https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus.txt

**Comment by funilrys** [comment]
@realodix Sorry for the waiting time. I was away from keyboards. I just created the repositories and invited you to join one of the internal teams so that you (or your team later) can configure the repository if needed.

Cheers!

P.S: I'm not closing this because the last part of the addition process was not verified yet.
